import Footer from '../app/components/Footer'
import NaviBar from '../app/components/NavBar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <link rel='shortcut icon' href='/images/favicon.ico' />
    <title>PokeNext</title>
      <body suppressHydrationWarning={true}>
        <NaviBar />
        <main style={{ minHeight: '70vh'} }> {children} </main>
        <Footer />
        </body>
    </html>
  )
}
